-- MySQL Script generated by MySQL Workbench
-- Mon Jun 26 18:11:58 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema sspger
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `sspger` ;

-- -----------------------------------------------------
-- Schema sspger
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `sspger` DEFAULT CHARACTER SET latin1 ;
USE `sspger` ;

-- -----------------------------------------------------
-- Table `sspger`.`cuerpo_academico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sspger`.`cuerpo_academico` (
  `idCuerpoAcademico` VARCHAR(15) NOT NULL,
  `nombre` VARCHAR(100) NOT NULL,
  `estado` INT(11) NOT NULL,
  PRIMARY KEY (`idCuerpoAcademico`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `sspger`.`anteproyecto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sspger`.`anteproyecto` (
  `idAnteproyecto` INT(11) NOT NULL AUTO_INCREMENT,
  `idCuerpoAcademico` VARCHAR(15) NULL DEFAULT NULL,
  `nombreProyecto` VARCHAR(300) NOT NULL,
  `descripcion` VARCHAR(5000) NULL DEFAULT NULL,
  `resultadosEsperados` VARCHAR(1000) NOT NULL,
  `duracionAproximada` INT(11) NOT NULL,
  `notas` VARCHAR(1000) NULL DEFAULT NULL,
  `requisitos` VARCHAR(1000) NOT NULL,
  `bibliografiaRecomendada` VARCHAR(5000) NULL DEFAULT NULL,
  `estadoAnteproyecto` VARCHAR(50) NULL DEFAULT NULL,
  `cupo` INT(11) NOT NULL,
  `modalidad` VARCHAR(45) NULL DEFAULT NULL,
  `descripcionTrabajoRecepcional` VARCHAR(5000) NULL DEFAULT NULL,
  `nombrePladea_Fei` VARCHAR(300) NULL DEFAULT NULL,
  `lineaInvestigacion` VARCHAR(1000) NULL DEFAULT NULL,
  PRIMARY KEY (`idAnteproyecto`),
  CONSTRAINT `idCuerpoAcadémicoAnteproyecto`
    FOREIGN KEY (`idCuerpoAcademico`)
    REFERENCES `sspger`.`cuerpo_academico` (`idCuerpoAcademico`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = latin1;

CREATE INDEX `idCuerpoAcadémicoAnteproyecto_idx` ON `sspger`.`anteproyecto` (`idCuerpoAcademico` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `sspger`.`archivo_entregable`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sspger`.`archivo_entregable` (
  `idarchivoentregable` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(1000) NOT NULL,
  `ruta` VARCHAR(1000) NOT NULL,
  `extension` VARCHAR(1000) NOT NULL,
  PRIMARY KEY (`idarchivoentregable`))
ENGINE = InnoDB
AUTO_INCREMENT = 11
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `sspger`.`trabajo_recepcional`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sspger`.`trabajo_recepcional` (
  `idTrabajoRecepcional` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(300) NOT NULL,
  `descripcion` VARCHAR(5000) NOT NULL,
  `modalidad` VARCHAR(45) NOT NULL,
  `estado` VARCHAR(30) NOT NULL,
  `resultados` VARCHAR(1000) NOT NULL,
  `idAnteproyecto` INT(11) NOT NULL,
  PRIMARY KEY (`idTrabajoRecepcional`),
  CONSTRAINT `idTrabajoRecepcionalAnteproyecto`
    FOREIGN KEY (`idAnteproyecto`)
    REFERENCES `sspger`.`anteproyecto` (`idAnteproyecto`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 12
DEFAULT CHARACTER SET = latin1;

CREATE INDEX `idAnteproyecto_TrabajoRecepcional_idx` ON `sspger`.`trabajo_recepcional` (`idAnteproyecto` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `sspger`.`avance`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sspger`.`avance` (
  `idavance` INT(11) NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(5000) NULL DEFAULT NULL,
  `fechaEntrega` DATETIME NOT NULL,
  `idArchivoAvance` INT(11) NOT NULL,
  PRIMARY KEY (`idavance`),
  CONSTRAINT `idArchivoAvance`
    FOREIGN KEY (`idArchivoAvance`)
    REFERENCES `sspger`.`archivo_entregable` (`idarchivoentregable`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = latin1;

CREATE INDEX `idArchivoAvance_idx` ON `sspger`.`avance` (`idArchivoAvance` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `sspger`.`cuenta_acceso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sspger`.`cuenta_acceso` (
  `correo` VARCHAR(320) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `estado` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`correo`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;

CREATE UNIQUE INDEX `correo_institucional_UNIQUE` ON `sspger`.`cuenta_acceso` (`correo` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `sspger`.`profesor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sspger`.`profesor` (
  `idUsuarioProfesor` INT(11) NOT NULL AUTO_INCREMENT,
  `correo` VARCHAR(320) NULL DEFAULT NULL,
  `nombre` VARCHAR(60) NULL DEFAULT NULL,
  `apellido` VARCHAR(60) NULL DEFAULT NULL,
  `numPersonal` VARCHAR(45) NOT NULL,
  `honorifico` VARCHAR(45) NULL DEFAULT NULL,
  `isAdmin` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`idUsuarioProfesor`),
  CONSTRAINT `correoProfesor`
    FOREIGN KEY (`correo`)
    REFERENCES `sspger`.`cuenta_acceso` (`correo`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = latin1;

CREATE UNIQUE INDEX `numPersonal_UNIQUE` ON `sspger`.`profesor` (`numPersonal` ASC) VISIBLE;

CREATE INDEX `correoProfesor_idx` ON `sspger`.`profesor` (`correo` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `sspger`.`asignacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sspger`.`asignacion` (
  `idAsignacion` INT(11) NOT NULL AUTO_INCREMENT,
  `idUsuarioProfesor` INT(11) NOT NULL,
  `idAvance` INT(11) NULL DEFAULT NULL,
  `titulo` VARCHAR(100) NULL DEFAULT NULL,
  `fechaInicia` DATETIME NULL DEFAULT NULL,
  `fechaFin` DATETIME NULL DEFAULT NULL,
  `fechaPublicacion` DATETIME NULL DEFAULT NULL,
  `descripcion` VARCHAR(5000) NULL DEFAULT NULL,
  `idTrabajoRecepcional` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`idAsignacion`),
  CONSTRAINT `idAsignacionTrabajoRecepcional`
    FOREIGN KEY (`idTrabajoRecepcional`)
    REFERENCES `sspger`.`trabajo_recepcional` (`idTrabajoRecepcional`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `idAvanceAsignacion`
    FOREIGN KEY (`idAvance`)
    REFERENCES `sspger`.`avance` (`idavance`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `idUsuarioProfesorAsignacion`
    FOREIGN KEY (`idUsuarioProfesor`)
    REFERENCES `sspger`.`profesor` (`idUsuarioProfesor`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 11
DEFAULT CHARACTER SET = latin1;

CREATE INDEX `idUsuarioProfesorAsignacion_idx` ON `sspger`.`asignacion` (`idUsuarioProfesor` ASC) VISIBLE;

CREATE INDEX `idAvanceAsignacion_idx` ON `sspger`.`asignacion` (`idAvance` ASC) VISIBLE;

CREATE INDEX `idAsignacionTrabajoRecepcional_idx` ON `sspger`.`asignacion` (`idTrabajoRecepcional` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `sspger`.`periodo_escolar`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sspger`.`periodo_escolar` (
  `idPeriodoEscolar` INT(11) NOT NULL AUTO_INCREMENT,
  `fechaInicio` DATE NOT NULL,
  `fechaFin` DATE NOT NULL,
  PRIMARY KEY (`idPeriodoEscolar`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `sspger`.`curso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sspger`.`curso` (
  `idCurso` VARCHAR(15) NOT NULL,
  `idPeriodoEscolar` INT(11) NOT NULL,
  `idUsuarioProfesor` INT(11) NULL DEFAULT NULL,
  `nombre` VARCHAR(60) NOT NULL,
  `nrc` VARCHAR(45) NOT NULL,
  `seccion` INT(11) NOT NULL,
  `bloque` INT(11) NOT NULL,
  `estado` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idCurso`),
  CONSTRAINT `idPeriodoEscolar`
    FOREIGN KEY (`idPeriodoEscolar`)
    REFERENCES `sspger`.`periodo_escolar` (`idPeriodoEscolar`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `idUsuarioProfesorCurso`
    FOREIGN KEY (`idUsuarioProfesor`)
    REFERENCES `sspger`.`profesor` (`idUsuarioProfesor`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;

CREATE INDEX `idPeriodoEscolar_idx` ON `sspger`.`curso` (`idPeriodoEscolar` ASC) VISIBLE;

CREATE INDEX `idUsuarioProfesorCurso_idx` ON `sspger`.`curso` (`idUsuarioProfesor` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `sspger`.`estudiante`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sspger`.`estudiante` (
  `idUsuarioEstudiante` INT(11) NOT NULL AUTO_INCREMENT,
  `correo_institucional` VARCHAR(320) NULL DEFAULT NULL,
  `nombre` VARCHAR(60) NOT NULL,
  `apellido` VARCHAR(60) NOT NULL,
  `matricula` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`idUsuarioEstudiante`),
  CONSTRAINT `correoEst`
    FOREIGN KEY (`correo_institucional`)
    REFERENCES `sspger`.`cuenta_acceso` (`correo`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 7
DEFAULT CHARACTER SET = latin1;

CREATE UNIQUE INDEX `matricula_UNIQUE` ON `sspger`.`estudiante` (`matricula` ASC) VISIBLE;

CREATE INDEX `correoestudiante_idx` ON `sspger`.`estudiante` (`correo_institucional` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `sspger`.`cursa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sspger`.`cursa` (
  `idCursa` INT(11) NOT NULL AUTO_INCREMENT,
  `idCurso` VARCHAR(15) NOT NULL,
  `idUsuarioEstudiante` INT(11) NOT NULL,
  PRIMARY KEY (`idCursa`),
  CONSTRAINT `idCurso`
    FOREIGN KEY (`idCurso`)
    REFERENCES `sspger`.`curso` (`idCurso`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `idUsuarioEstudianteCursa`
    FOREIGN KEY (`idUsuarioEstudiante`)
    REFERENCES `sspger`.`estudiante` (`idUsuarioEstudiante`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 21
DEFAULT CHARACTER SET = latin1;

CREATE INDEX `idCurso_idx` ON `sspger`.`cursa` (`idCurso` ASC) VISIBLE;

CREATE INDEX `idUsuarioEstudianteCursa_idx` ON `sspger`.`cursa` (`idUsuarioEstudiante` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `sspger`.`estudiante_anteproyecto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sspger`.`estudiante_anteproyecto` (
  `idEstudianteAnteproyecto` INT(11) NOT NULL AUTO_INCREMENT,
  `idEstudiante` INT(11) NOT NULL,
  `idAnteproyecto` INT(11) NOT NULL,
  `estadoEstudiante` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idEstudianteAnteproyecto`),
  CONSTRAINT `idAnteproyectoEA`
    FOREIGN KEY (`idAnteproyecto`)
    REFERENCES `sspger`.`anteproyecto` (`idAnteproyecto`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `idEstudianteEA`
    FOREIGN KEY (`idEstudiante`)
    REFERENCES `sspger`.`estudiante` (`idUsuarioEstudiante`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 64
DEFAULT CHARACTER SET = latin1;

CREATE INDEX `idEstudianteEA_idx` ON `sspger`.`estudiante_anteproyecto` (`idEstudiante` ASC) VISIBLE;

CREATE INDEX `idAnteproyectoEA_idx` ON `sspger`.`estudiante_anteproyecto` (`idAnteproyecto` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `sspger`.`estudiante_trabajo_recepcional`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sspger`.`estudiante_trabajo_recepcional` (
  `idEstudianteTrabajoRecepcional` INT(11) NOT NULL AUTO_INCREMENT,
  `idEstudiante` INT(11) NULL DEFAULT NULL,
  `idTrabajoRecepcional` INT(11) NOT NULL,
  PRIMARY KEY (`idEstudianteTrabajoRecepcional`),
  CONSTRAINT `idEstudianteAnteproyecto`
    FOREIGN KEY (`idEstudiante`)
    REFERENCES `sspger`.`estudiante` (`idUsuarioEstudiante`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `idTrabajoRecepcionalEst`
    FOREIGN KEY (`idTrabajoRecepcional`)
    REFERENCES `sspger`.`trabajo_recepcional` (`idTrabajoRecepcional`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 80
DEFAULT CHARACTER SET = latin1;

CREATE INDEX `idEstudianteAnteproyecto_idx` ON `sspger`.`estudiante_trabajo_recepcional` (`idEstudiante` ASC) VISIBLE;

CREATE INDEX `idTrabajoRecepcionalEst_idx` ON `sspger`.`estudiante_trabajo_recepcional` (`idTrabajoRecepcional` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `sspger`.`evalua`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sspger`.`evalua` (
  `idEvalua` INT(11) NOT NULL AUTO_INCREMENT,
  `idAvance` INT(11) NOT NULL,
  `retroalimentacion` VARCHAR(1000) NOT NULL,
  PRIMARY KEY (`idEvalua`),
  CONSTRAINT `idAvanceEvalua`
    FOREIGN KEY (`idAvance`)
    REFERENCES `sspger`.`avance` (`idavance`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = latin1;

CREATE INDEX `idAvanceEvalua_idx` ON `sspger`.`evalua` (`idAvance` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `sspger`.`lgac`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sspger`.`lgac` (
  `idLGAC` VARCHAR(30) NOT NULL,
  `nombre` VARCHAR(80) NOT NULL,
  `descripcion` VARCHAR(500) NOT NULL,
  PRIMARY KEY (`idLGAC`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `sspger`.`lgac_anteproyecto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sspger`.`lgac_anteproyecto` (
  `idlgac_anteproyecto` INT(11) NOT NULL AUTO_INCREMENT,
  `idAnteproyecto` INT(11) NOT NULL,
  `idlgac` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`idlgac_anteproyecto`),
  CONSTRAINT `idAnteproyectoLGAC`
    FOREIGN KEY (`idAnteproyecto`)
    REFERENCES `sspger`.`anteproyecto` (`idAnteproyecto`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `idLgacAnteproyecto`
    FOREIGN KEY (`idlgac`)
    REFERENCES `sspger`.`lgac` (`idLGAC`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 23
DEFAULT CHARACTER SET = latin1;

CREATE INDEX `idLgacAnteproyecto_idx` ON `sspger`.`lgac_anteproyecto` (`idlgac` ASC) VISIBLE;

CREATE INDEX `idAnteproyectoLGAC_idx` ON `sspger`.`lgac_anteproyecto` (`idAnteproyecto` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `sspger`.`profesor_anteproyecto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sspger`.`profesor_anteproyecto` (
  `idProfesorAnteproyecto` INT(11) NOT NULL AUTO_INCREMENT,
  `idAnteproyecto` INT(11) NOT NULL,
  `idUsuarioProfesor` INT(11) NOT NULL,
  `rol` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`idProfesorAnteproyecto`),
  CONSTRAINT `idAnteproyectoProfesor`
    FOREIGN KEY (`idAnteproyecto`)
    REFERENCES `sspger`.`anteproyecto` (`idAnteproyecto`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `idUsuarioProfesorAnteproyecto`
    FOREIGN KEY (`idUsuarioProfesor`)
    REFERENCES `sspger`.`profesor` (`idUsuarioProfesor`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 12
DEFAULT CHARACTER SET = latin1;

CREATE INDEX `idAnteproyectoProfesor_idx` ON `sspger`.`profesor_anteproyecto` (`idAnteproyecto` ASC) VISIBLE;

CREATE INDEX `idUsuarioProfesorAnteproyecto_idx` ON `sspger`.`profesor_anteproyecto` (`idUsuarioProfesor` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `sspger`.`profesor_cuerpo_academico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sspger`.`profesor_cuerpo_academico` (
  `idProfesorCuerpoAcademico` INT(11) NOT NULL AUTO_INCREMENT,
  `idCuerpoAcadémico` VARCHAR(15) NOT NULL,
  `idUsuarioProfesor` INT(11) NOT NULL,
  `rol` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idProfesorCuerpoAcademico`),
  CONSTRAINT `idCuerpoAcadémicoProfesor`
    FOREIGN KEY (`idCuerpoAcadémico`)
    REFERENCES `sspger`.`cuerpo_academico` (`idCuerpoAcademico`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `idUsuarioProfesorCuerpoAcademico`
    FOREIGN KEY (`idUsuarioProfesor`)
    REFERENCES `sspger`.`profesor` (`idUsuarioProfesor`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 15
DEFAULT CHARACTER SET = latin1;

CREATE INDEX `idCuerpoAcadémicoProfesor_idx` ON `sspger`.`profesor_cuerpo_academico` (`idCuerpoAcadémico` ASC) VISIBLE;

CREATE INDEX `idUsuarioProfesorCuerpoAcademico_idx` ON `sspger`.`profesor_cuerpo_academico` (`idUsuarioProfesor` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `sspger`.`valida`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sspger`.`valida` (
  `idValida` INT(11) NOT NULL AUTO_INCREMENT,
  `idUsuarioProfesor` INT(11) NOT NULL,
  `idAnteproyecto` INT(11) NOT NULL,
  PRIMARY KEY (`idValida`),
  CONSTRAINT `idAnteproyectoValidado`
    FOREIGN KEY (`idAnteproyecto`)
    REFERENCES `sspger`.`anteproyecto` (`idAnteproyecto`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `idUsuarioProfesorValida`
    FOREIGN KEY (`idUsuarioProfesor`)
    REFERENCES `sspger`.`profesor` (`idUsuarioProfesor`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 11
DEFAULT CHARACTER SET = latin1;

CREATE INDEX `idUsuarioProfesorValida_idx` ON `sspger`.`valida` (`idUsuarioProfesor` ASC) VISIBLE;

CREATE INDEX `idAnteproyectoValidado_idx` ON `sspger`.`valida` (`idAnteproyecto` ASC) VISIBLE;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
